version: "3.9"

services:
  backend:
    build: ./quiz-api
    container_name: quiz-api
    environment:
      POSTGRES_DB: quiz
      POSTGRES_USER: quiz-user
      POSTGRES_PASSWORD: quiz-password
      POSTGRES_HOST: database
      FLASK_ENV: production
      FLASK_DEBUG: "0"
    ports:
      - "5001:5000"
    depends_on:
      - database
    restart: unless-stopped
    networks:
      - quiz-net

  database:
    image: postgres:15
    container_name: quiz-db
    environment:
      POSTGRES_DB: quiz
      POSTGRES_USER: quiz-user
      POSTGRES_PASSWORD: quiz-password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quiz-net

  frontend:
    build:
      context: ./quiz-ui
      args:
        VITE_API_URL: http://localhost:5001
    container_name: quiz-ui
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - quiz-net

volumes:
  postgres_data:

networks:
  quiz-net:
